/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/portfolio_scene_baked_final2.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/portfolio_scene_baked_final2.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Desk"
          position={[-0.071, -0.025, -1.505]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Plane001_Plane002_BlackWood001"
            geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
            material={materials["BlackWood.001"]}
          />
          <mesh
            name="Plane001_Plane002_BlackWood001_1"
            geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
            material={materials["BlackCoatSteel.001"]}
          />
          <mesh
            name="Plane001_Plane002_BlackWood001_2"
            geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
            material={materials["GrayPlastic.001"]}
          />
          <mesh
            name="Plane001_Plane002_BlackWood001_3"
            geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
            material={materials["WhiteSteelScrew.001"]}
          />
          <mesh
            name="Plane001_Plane002_BlackWood001_4"
            geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
            material={materials["BlackPlastic.001"]}
          />
        </group>
        <group
          name="keyboard"
          position={[-0.095, 0.934, -1.282]}
          rotation={[0, -0.165, 0]}
        >
          <mesh
            name="mesh425587018"
            geometry={nodes.mesh425587018.geometry}
            material={materials["mat21.004"]}
          />
          <mesh
            name="mesh425587018_1"
            geometry={nodes.mesh425587018_1.geometry}
            material={materials["mat22.001"]}
          />
          <mesh
            name="mesh425587018_2"
            geometry={nodes.mesh425587018_2.geometry}
            material={materials["mat9.002"]}
          />
          <mesh
            name="mesh425587018_3"
            geometry={nodes.mesh425587018_3.geometry}
            material={materials["mat16.001"]}
          />
        </group>
        <group
          name="iMac"
          position={[0.226, 0.92, -1.662]}
          rotation={[Math.PI, -1.099, Math.PI]}
        >
          <mesh
            name="iMac_1"
            geometry={nodes.iMac_1.geometry}
            material={materials.Screen}
          />
          <mesh
            name="iMac_1_1"
            geometry={nodes.iMac_1_1.geometry}
            material={materials.ScreenBlack}
          />
          <mesh
            name="iMac_1_2"
            geometry={nodes.iMac_1_2.geometry}
            material={materials.iMacBody}
          />
        </group>
        <mesh
          name="Comp_Mouse"
          geometry={nodes.Comp_Mouse.geometry}
          material={materials["lambert3SG.003"]}
          position={[-0.077, 0.053, 0.03]}
        />
        <group name="plant" position={[-0.78, 1.071, -1.61]}>
          <mesh
            name="mesh24448074"
            geometry={nodes.mesh24448074.geometry}
            material={materials["mat9.003"]}
          />
          <mesh
            name="mesh24448074_1"
            geometry={nodes.mesh24448074_1.geometry}
            material={materials["mat20.001"]}
          />
          <mesh
            name="mesh24448074_2"
            geometry={nodes.mesh24448074_2.geometry}
            material={materials["mat21.005"]}
          />
        </group>
        <group
          name="Houseplant_7"
          position={[-1.599, -0.072, -1.626]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Houseplant_7_1"
            geometry={nodes.Houseplant_7_1.geometry}
            material={materials["Black.001"]}
          />
          <mesh
            name="Houseplant_7_2"
            geometry={nodes.Houseplant_7_2.geometry}
            material={materials["Brown.001"]}
          />
          <mesh
            name="Houseplant_7_3"
            geometry={nodes.Houseplant_7_3.geometry}
            material={materials["Plant_Green.001"]}
          />
        </group>
        <group
          name="Chair"
          position={[-0.196, -0.073, -0.874]}
          rotation={[0, -0.376, 0]}
        >
          <mesh
            name="Node-Mesh"
            geometry={nodes["Node-Mesh"].geometry}
            material={materials.Office_Cha}
          />
          <mesh
            name="Node-Mesh_1"
            geometry={nodes["Node-Mesh_1"].geometry}
            material={materials.Office_Cha_1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/portfolio_scene_baked_final2.glb");
