export { default as ContactForm } from "./ContactForm"
export { default as ThankYou } from "./ThankYou"
export { default as Typed } from "./Typed"
export { default as ExperienceDetails } from "./ExperienceDetails"
export { default as Avatar } from "./Avatar"
export { default as Main } from "./Main"
export { default as Office } from "./Office"